---
title: "table_with_effectsizes"
author: "Sarah"
date: "2024-01-26"
output: html_document
---

## Hallo Jan Hallo Sarah
# set up and load in data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# 30.01.2024

# Sarah

source("data_cleaning.R") # get up-to date dataset

str(working_data)
# 
# #filter treatments we are interested in
# working_data <- full_data %>% 
#   filter(treatment %in% c("CTL","OTC","SNOWFENCE","OTCxSNOWFENCE"))

working_data$month <- month(working_data$flux_date)

#override initial flux_id as we have no seperation in growing season
working_data$flux_id <- as.factor(paste(working_data$site_id, working_data$year,working_data$c_loss, sep = "_"))

# #working_data$monthseason <- ifelse(working_data$month <= 3,"NGS",
#                                    ifelse(working_data$month <= 5, "Shoulder",
#                                           ifelse(working_data$month <= 9, "GS",
#                                                  ifelse(working_data$month <= 11, "Shoulder", "NGS"))))
```

```{r calculate N, mean and sd}

# Define variables of interest
variables_of_interest <- c("co2")

# Summarize multiple variables
summary_stats <- working_data %>%
  group_by(site_id, year, treatment,flux_id, month) %>%
  dplyr::summarize_at(vars(variables_of_interest),
                      list(mean = ~mean(., na.rm = TRUE),
                           sd = ~sd(., na.rm = TRUE),
                           n = ~n()))

# Separate data for treatments OTC and SF using filter
ctl <- summary_stats %>% dplyr::filter(treatment == "CTL")
otc <- summary_stats %>% dplyr::filter(treatment == "OTC")
snow_fence <- summary_stats %>% dplyr::filter(treatment == "SNOWFENCE")
snow_fence_otc <- summary_stats %>% dplyr::filter(treatment == "OTCxSNOWFENCE")

effect_df1 <- full_join(otc, snow_fence, by = c("site_id", "year","flux_id", "month"),
                       suffix = c("_otc", "_sf"))

effect_df2 <- full_join(ctl, snow_fence_otc, by = c("site_id", "year","flux_id", "month"),
                       suffix = c("_ctl", "_otc_sf"))

effect_df <- full_join(effect_df1, effect_df2, by = c("site_id", "year","flux_id", "month"),
                       suffix = c("", ""))
```

```{r effectsize calc}
otc_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = mean_otc,
    # mean richness at invaded sites
    n1i = n_otc,
    # invaded site sample size
    sd1i = sd_otc,
    # invaded site SD
    m2i = mean_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = sd_ctl,
    # control site SD
    data = effect_df # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_effect_sizes) <- gsub("yi", "yi_otc",colnames(otc_effect_sizes))
colnames(otc_effect_sizes) <- gsub("vi", "vi_otc",colnames(otc_effect_sizes))

sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = mean_sf,
    # mean richness at invaded sites
    n1i = n_sf,
    # invaded site sample size
    sd1i = sd_sf,
    # invaded site SD
    m2i = mean_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = sd_ctl,
    # control site SD
    data = effect_df # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(sf_effect_sizes) <- gsub("yi", "yi_sf",colnames(sf_effect_sizes))
colnames(sf_effect_sizes) <- gsub("vi", "vi_sf",colnames(sf_effect_sizes))

otc_sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = mean_otc_sf,
    # mean richness at invaded sites
    n1i = n_otc_sf,
    # invaded site sample size
    sd1i = sd_otc_sf,
    # invaded site SD
    m2i = mean_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = sd_ctl,
    # control site SD
    data = effect_df # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_sf_effect_sizes) <- gsub("yi", "yi_otc_sf",colnames(otc_sf_effect_sizes))
colnames(otc_sf_effect_sizes) <- gsub("vi", "vi_otc_sf",colnames(otc_sf_effect_sizes))
```


```{r overview datapoints}
library(dplyr)

result_table <- working_data %>%
  group_by(site_id, treatment) %>%
  summarize(across(everything(), ~sum(!is.na(.))))

print(result_table)
#write.csv(result_table, "data_overview.csv")
```

# run multivariate effects model
#SF
```{r SF}
#total
SF_total <- rma.mv(yi_sf, vi_sf, 
                   mods= ~site_id,
                random=list(~ 1 | site_id, 
                            ~ year | site_id), 
                struct="CAR", 
                data=sf_effect_sizes)
summary(SF_total)
forest(SF_total)
predict(SF_total)

#orchard plot
sf_effect_sizes$site_id <- as.factor(sf_effect_sizes$site_id)
SF_na <- sf_effect_sizes[complete.cases(sf_effect_sizes$yi_sf), ]
library(orchaRd)
model_SF<-orchaRd::mod_results(SF_total, mod="site_id", group="site_id", data=SF_na)
orchard_plot(model_SF, mod = "site_id", group = "site_id", 
             xlab = "Ecosystem respiration", transfm = "none",data=sf_effect_sizes,
             trunk.size = 6)+
#scale_y_continuous(limits = c(-4, 4)) +
  theme_minimal()+
  theme(text = element_text(family = "Arial"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))+
  theme(legend.position= c(0.5, 0.05),
        legend.justification = c(0,1),
        legend.key.size = unit(1, "mm")) +
  theme(legend.direction="horizontal",
        legend.position="bottom",
        legend.title = element_text(size =10),
        legend.text = element_text(size = 10))

# #GS
# SF_GS <- rma.mv(yi_sf, vi_sf, 
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(sf_effect_sizes, monthseason=="GS",)
# )
# 
# forest(SF_GS)
# summary(SF_GS)
# predict(SF_GS)
# #NGS
# SF_NGS <- rma.mv(yi_sf, vi_sf,
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(sf_effect_sizes, monthseason=="NGS",)
# )
# summary(SF_NGS)
# predict(SF_NGS)
# #Shoulder
# SF_sh <- rma.mv(yi_sf, vi_sf, 
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(sf_effect_sizes, monthseason=="Shoulder",)
# )
# summary(SF_sh)
# forest(SF_sh)
# predict(SF_sh)

```

#OTC
```{r  OTC}
#total
OTC_total <- rma.mv(yi_otc, vi_otc, 
                    mods= ~as.factor(site_id),
                    random=list(~ 1 | site_id,
                                ~ year | site_id), 
                    struct="CAR", 
                    data=otc_effect_sizes,
                    control = list(iter.max = 100000))  # Increase iterations

summary(OTC_total)
forest(OTC_total)
predict(OTC_total)


OTC_na <- otc_effect_sizes[complete.cases(otc_effect_sizes$yi_otc), ]
library(orchaRd)
model_OTC<-orchaRd::mod_results(OTC_total, mod = "site_id", group = "site_id", data=OTC_na)
orchard_plot(model_OTC, mod = "site_id", group = "site_id", 
             xlab = "Ecosystem respiration", transfm = "none",data=sf_effect_sizes,
             trunk.size = 6)
#scale_y_continuous(limits = c(-4, 4)) +
  theme_minimal()+
  theme(text = element_text(family = "Arial"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))+
  theme(legend.position= c(0.5, 0.05),
        legend.justification = c(0,1),
        legend.key.size = unit(1, "mm")) +
  theme(legend.direction="horizontal",
        legend.position="bottom",
        legend.title = element_text(size =10),
        legend.text = element_text(size = 10))
# #GS
# OTC_GS <- rma.mv(yi_otc, vi_otc, 
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(otc_effect_sizes, monthseason=="GS",)
# )
# 
# forest(OTC_GS)
# summary(OTC_GS)
# predict(OTC_GS)
# #NGS
# OTC_NGS <- rma.mv(yi_otc, vi_otc, 
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(otc_effect_sizes, monthseason=="NGS",)
# )
# summary(OTC_NGS)
# predict(OTC_NGS)
# #Shoulder
# OTC_sh <- rma.mv(yi_otc, vi_otc, 
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(otc_effect_sizes, monthseason=="Shoulder",)
# )
# summary(OTC_sh)
# forest(OTC_sh)
# predict(OTC_sh)

```
http://127.0.0.1:35789/graphics/plot_zoom_png?width=1200&height=900
#SFxOTC
```{r SFxOTC}

#total
OTC_SF_total <- rma.mv(yi_otc_sf, vi_otc_sf, 
                       mods= ~site_id,
                random=list(~ 1 | site_id, 
                            ~ year | site_id), 
                struct="CAR", 
                data=otc_sf_effect_sizes)
summary(OTC_SF_total)
forest(OTC_SF_total,
       overall = TRUE)
predict(OTC_SF_total)

OTC_SF_na <- otc_sf_effect_sizes[complete.cases(otc_sf_effect_sizes$yi_otc_sf), ]
library(orchaRd)
model_OTC_SF<-orchaRd::mod_results(OTC_SF_total, mod="site_id", group="site_id", data=OTC_SF_na)
orchard_plot(model_OTC_SF, mod = "site_id", group = "site_id", 
             xlab = "Ecosystem respiration", transfm = "none",data=sf_effect_sizes,
             trunk.size = 6)+
#scale_y_continuous(limits = c(-4, 4)) +
  theme_minimal()+
  theme(text = element_text(family = "Arial"),
        axis.text = element_text(size = 15),
        axis.title = element_text(size = 15))+
  theme(legend.position= c(0.5, 0.05),
        legend.justification = c(0,1),
        legend.key.size = unit(1, "mm")) +
  theme(legend.direction="horizontal",
        legend.position="bottom",
        legend.title = element_text(size =10),
        legend.text = element_text(size = 10))

# #GS
# OTC_SF_GS <- rma.mv(yi_otc_sf, vi_otc_sf,  
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(otc_sf_effect_sizes, monthseason=="GS",)
# )
# 
# forest(OTC_SF_GS)
# summary(OTC_SF_GS)
# predict(OTC_SF_GS)
# #NGS
# OTC_SF_NGS <- rma.mv(yi_otc_sf, vi_otc_sf, 
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(otc_sf_effect_sizes, monthseason=="NGS",)
# )
# summary(OTC_SF_NGS)
# predict(OTC_SF_NGS)
# #Shoulder
# OTC_SF_sh <- rma.mv(yi_otc_sf, vi_otc_sf,  
#                 random=list(~ 1 | site_id, 
#                             ~ year | site_id), 
#                 struct="CAR", 
#                 data=subset(otc_sf_effect_sizes, monthseason=="Shoulder",)
# )
# summary(OTC_SF_sh)
# forest(OTC_SF_sh)
# predict(OTC_SF_sh)

```
## MAP
```{r map}
#### circumpolar map #####
library(ggplot2)
library(rgdal)                                                                                                      
library(raster)
library(dplyr)

sessionInfo()

# # add country code
# library(countrycode)
# dat$Code<- countrycode(dat$Country, origin = 'country.name', destination = 'iso3c')
# #does not recognize Svalbard -> manually change NA to SJM
# dat$Code[is.na(dat$Code)] <- "SJM"
# 
# # number of years as radius
# years<-dat %>% dplyr::count(site_ID) 
# #rename n in "number of experiments"
# #merge with dat
# dat<-full_join(dat,years)
# n<-as.numeric(dat$n)
# 
# # observations per site as color gradient
# obs<-dat %>% dplyr::group_by(Site_ID)  %>% 
#   summarise(obs_sum = sum(Nr_Obs))
# 
# 
# # observations per site as color gradient
# sumi<-dat %>% dplyr::group_by(Site_ID)  %>% 
#   summarise(obs_sum = sum(Nr_Obs),
#             n = n(),
#             Longitude..DD. = unique(Longitude..DD.),
#             Latitude..DD. = unique(Latitude..DD.),
#             Country = unique(Country))
# #rename n in "number of experiments"
# #merge with dat
# dat<-full_join(dat,obs)
# obs_sum<-as.numeric(dat$obs_sum)
# 
# dat$Nr_Obs

working_data$n_coord_site<-as.numeric(working_data$n_coord_site)
unique_data <- distinct(working_data, site_id, e_coord_site, n_coord_site, treatment)  # Replace 'lon' and 'lat' with your coordinate column names

# get map data
thismap = map_data("world")

# Defines the x axes required
x_lines <- seq(-120,180, by = 60)

# Now modify the ggplot code
map <- ggplot() +
  geom_polygon(data = thismap, aes(x = long, y = lat, group = group), fill = "lightgrey", colour = "lightgrey") +
  
  # Convert to polar coordinates
  coord_map("ortho", orientation = c(90, 0, 0)) +
  scale_y_continuous(breaks = seq(30, 90, by = 10), labels = NULL) +
  
  # Adds points for all treatments except "OTCxSNOWFENCE"
  geom_point(data=subset(unique_data, treatment != "CTL" & treatment != "OTCxSNOWFENCE"), aes(x=e_coord_site, y=n_coord_site,   
              group=treatment, 
              fill=treatment,
              pch=treatment  # Map the shape to the new shape column
              ),
       color="black",
       alpha=0.6,
       size=3) +  
  
  # Adds points for "OTCxSNOWFENCE" with no transparency
  geom_point(data=subset(unique_data, treatment == "OTCxSNOWFENCE"), aes(x=e_coord_site, y=n_coord_site,   
              group=treatment, 
              fill=treatment,
            pch=treatment  # Map the shape to the new shape column
              ),
       color="black",
       alpha=1,  # No transparency
       size=3.2) +  
  
  # geom_point(data=subset(unique_data, treatment != "CTL"), aes(x=e_coord_site, y=n_coord_site,   
  #             group=treatment, 
  #             fill=treatment,
  #             pch=treatment  # Map the pch to the new shape column
  #             ),
  #      color="black",
  #      alpha=0.6,
  #      size=3) +  
  scale_fill_viridis_d(name = "treatment", limits =c("OTC","OTCxSNOWFENCE","SNOWFENCE"), direction=-1) + # add color gradient
  scale_shape_manual(values = c(21, 22, 24), limits =c("OTC","OTCxSNOWFENCE","SNOWFENCE")) +  # Define the shapes manually
  
  # Removes Axes and labels
  scale_x_continuous(breaks = NULL) +
  xlab("") +
  ylab("") +
  
  # Adds labels
  geom_text(aes(x = 180, y = seq(45, 85, by = 20), hjust = -0.2, label = paste0(seq(45, 85, by = 20), "°N"))) +
  geom_text(aes(x = x_lines, y = 15, label = c("120°W", "60°W", "0°", "60°E", "120°E", "180°W"))) +
  
  # Adds axes
  geom_segment(aes(y = 10, yend = 90, x = x_lines, xend = x_lines), linetype = "dashed") +
  
  # Change theme to remove axes and ticks
  theme(panel.background = element_blank(),
    panel.grid.major = element_line(size = 0.25, linetype = 'dashed',
                    colour = "darkgrey"),
    axis.ticks=element_blank(),
    legend.position = "top") 

```

