---
title: "effectsize_warming_year_round"
author: "Jan"
date: "2024-01-24"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# 23.01.2024

# Jan 

source("data_cleaning.R") # get up-to date dataset

working_data$month <- month(working_data$flux_date)





working_data$month <- month(working_data$flux_date)


working_data$monthseason <- ifelse(working_data$month <= 3,"NGS",
                                   ifelse(working_data$month <= 5, "Shoulder",
                                          ifelse(working_data$month <= 9, "GS",
                                                 ifelse(working_data$month <= 11, "Shoulder", "NGS"))))
```



```{r treatments}
ggplot(working_data) +
  geom_bar(aes(x=treatment,fill=site_id),stat = "count") + 
  scale_fill_viridis_d(option = "turbo")+
  theme_classic()
```
```{r treatments}
ggplot(working_data[working_data$site_id != "ALA_1",]) +
  geom_bar(aes(x=treatment,fill=site_id),stat = "count") + 
  scale_fill_viridis_d(option = "turbo")+
  theme_classic()
```
```{r treatments}
ggplot(working_data[working_data$site_id != "ALA_1" & working_data$treatment %in% c("SNOWFENCE","OTCxSNOWFENCE"),]) +
  geom_bar(aes(x=treatment,fill=site_id),stat = "count") + 
  scale_fill_viridis_d(option = "turbo")+
  theme_classic()
```
```{r treatments}
ggplot(working_data[working_data$site_id != "ALA_1" & working_data$treatment %in% c("SNOWFENCE","OTCxSNOWFENCE"),]) +
  geom_bar(aes(x=treatment,fill=site_id),stat = "count") + 
  scale_fill_viridis_d(option = "turbo")+
  facet_wrap(~monthseason,scales="free")+
  theme_classic()
```
```{r treatments}
ggplot(working_data[working_data$site_id != "ALA_1" & working_data$treatment %in% c("SNOWFENCE","OTCxSNOWFENCE"),]) +
  geom_bar(aes(x=month,fill=site_id),stat = "count") + 
  scale_fill_viridis_d(option = "turbo")+
  facet_wrap(~treatment,scales="free")+
  theme_classic()
```
```{r treatments}
ggplot(working_data[working_data$site_id != "ALA_1" & working_data$treatment %in% c("OTC","SNOWFENCE","OTCxSNOWFENCE"),]) +
  geom_bar(aes(x=month,fill=site_id),stat = "count") + 
  scale_fill_viridis_d(option = "turbo")+
  facet_wrap(~treatment,scales="free")+
  theme_classic()
```


```{r months, echo=FALSE}
# ggplot(working_data) +
# 
#   geom_bar(aes(x=month, fill = site_id),stat = "count") + 
#   facet_wrap(~monthseason,scales="free")+
#   theme_classic()

plotdata <- working_data %>% 
  group_by(site_id, year,month,treatment) %>% 
  dplyr::summarise(n=n())
ggplot(plotdata) +
  geom_bar(aes(x=month, fill = site_id),stat = "count") + 
  facet_wrap(~treatment,scales="free")+ 

  theme_classic()
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r preps}
monthly <- working_data %>%
  group_by(site_id,year,month) %>% 
  dplyr::summarise(n_ctl = sum(treatment == "CTL",na.rm=T),
                   n_otc = sum(treatment == "OTC",na.rm=T),
                   n_sf = sum(treatment == "SNOWFENCE",na.rm=T),
                   n_otc_sf = sum(treatment == "OTCxSNOWFENCE",na.rm=T),
                   m_ctl = mean(co2[treatment == "CTL"],na.rm=T),
                   m_otc = mean(co2[treatment == "OTC"],na.rm=T),
                   m_sf = mean(co2[treatment == "SNOWFENCE"],na.rm=T),
                   m_otc_sf = mean(co2[treatment == "OTCxSNOWFENCE"],na.rm=T),
                   s_ctl = sd(co2[treatment == "CTL"],na.rm=T),
                   s_otc = sd(co2[treatment == "OTC"],na.rm=T),
                   s_sf = sd(co2[treatment == "SNOWFENCE"],na.rm=T),
                   s_otc_sf = sd(co2[treatment == "OTCxSNOWFENCE"],na.rm=T))

monthly_otc <- monthly %>% filter(!is.na(m_otc))
monthly_otc <- monthly_otc[,-c(grep("sf",colnames(monthly_otc)))]

monthly_sf <- monthly %>% filter(!is.na(m_sf))
monthly_sf <- monthly_sf[,-c(grep("otc",colnames(monthly_sf)))]

monthly_otc_sf <- monthly %>% filter(!is.na(m_otc_sf))
monthly_otc_sf <- monthly_otc_sf[,c(1,2,3,c(grep("ctl|otc_sf",colnames(monthly_otc_sf))))]


```
lets go 
```{r effectsize calc}
otc_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_otc,
    # mean richness at invaded sites
    n1i = n_otc,
    # invaded site sample size
    sd1i = s_otc,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = monthly_otc # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_effect_sizes) <- gsub("yi", "yi_otc",colnames(otc_effect_sizes))
colnames(otc_effect_sizes) <- gsub("vi", "vi_otc",colnames(otc_effect_sizes))

sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_sf,
    # mean richness at invaded sites
    n1i = n_sf,
    # invaded site sample size
    sd1i = s_sf,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = monthly_sf # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(sf_effect_sizes) <- gsub("yi", "yi_sf",colnames(sf_effect_sizes))
colnames(sf_effect_sizes) <- gsub("vi", "vi_sf",colnames(sf_effect_sizes))

otc_sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_otc_sf,
    # mean richness at invaded sites
    n1i = n_otc_sf,
    # invaded site sample size
    sd1i = s_otc_sf,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = monthly_otc_sf # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_sf_effect_sizes) <- gsub("yi", "yi_otc_sf",colnames(otc_sf_effect_sizes))
colnames(otc_sf_effect_sizes) <- gsub("vi", "vi_otc_sf",colnames(otc_sf_effect_sizes))



```

# models

```{r yo}
#otc
otc_total <- rma.mv(yi_otc, vi_otc, 
                   random=list(~ 1 | site_id, 
                            ~ year | site_id), 
                   struct="CAR",
                   mods = ~month,
                   data=otc_effect_sizes)
summary(otc_total)
forest(otc_total)
ggplot(otc_effect_sizes) +
  geom_boxplot(aes(x=as.factor(month), y= yi_otc))+
  facet_wrap(~site_id)
  

#SF
sf_total <- rma.mv(yi_sf, vi_sf, 
                   random=list(~ 1 | month, 
                            ~ year | month), 
                   struct="CAR",
                   data=sf_effect_sizes)
summary(sf_total)
forest(sf_total)
ggplot(sf_effect_sizes) +
  geom_boxplot(aes(x=as.factor(month), y= yi_sf,fill=site_id))

#otc_sf
otc_sf_total <- rma.mv(yi_otc_sf, vi_otc_sf, 
                   random=list(~ 1 | month, 
                            ~ year | month), 
                   struct="CAR",
                   data=otc_sf_effect_sizes)
summary(otc_sf_total)
forest(otc_sf_total)
ggplot(otc_sf_effect_sizes) +
  geom_boxplot(aes(x=as.factor(month), y= yi_otc_sf,,fill=site_id))

```



```{r }
ggplot(otc_effect_sizes)+
  geom_boxplot(aes(x=as.factor(month),y=yi_otc),varwidth = TRUE)+
  geom_jitter(aes(x=as.factor(month),y=yi_otc,color=site_id),width = 0.1,alpha = 0.5)+
  facet_wrap(~site_id)+
  theme_minimal()

# otc_model <- lmer(yi_otc ~ month + (1|site_id) + (1|year), 
#               weights = 1 / vi_otc^2,
#               data = otc_effect_sizes)
# summary(otc_model)
```
```{r}
ggplot(otc_effect_sizes[otc_effect_sizes$site_id == "GRE_6",])+
    #geom_boxplot(aes(x=as.factor(month),y=yi_otc),varwidth = TRUE)+
    #geom_jitter(aes(x=as.factor(month),y=yi_otc,color=as.factor(year)),size =4)+
    geom_smooth(aes(x=month,y=yi_otc,color=as.factor(year)),method="lm",se=F)+
    facet_wrap(~site_id)+
    theme_minimal()
```



```{r }
ggplot(sf_effect_sizes)+
  geom_boxplot(aes(x=as.factor(month),y=yi_sf),varwidth = TRUE)+
  geom_jitter(aes(x=as.factor(month),y=yi_sf,color=site_id),width = 0.1,alpha = 0.5)+
  theme_minimal()
```

```{r}
ggplot(otc_sf_effect_sizes)+
  geom_boxplot(aes(x=as.factor(month),y=yi_otc_sf),varwidth = T)+
  geom_jitter(aes(x=as.factor(month),y=yi_otc_sf,color=site_id),width = 0.1,alpha = 0.5)+
  theme_minimal()
```


```{r}
full_effect_size <- merge(otc_effect_sizes[,c(1,2,3,10,11)],
                          sf_effect_sizes[,c(1,2,3,10,11)],
                          by = c("site_id", "year", "month"),
                          all = T)

full_effect_size <- merge(full_effect_size ,
                          otc_sf_effect_sizes[,c(1,2,3,10,11)],
                          by = c("site_id", "year", "month"),
                          all = T)

stacked_effect <- full_effect_size %>% 
  gather(treatment, effectsize, yi_otc,yi_sf,yi_otc_sf)

```

hello i changed something


```{r}
ggplot(full_effect_size)+
  geom_boxplot(aes(x=as.factor(month),y=yi_otc_sf),fill="red",alpha=0.8, varwidth = T)+
  geom_boxplot(aes(x=as.factor(month),y=yi_otc),fill="lightgreen",alpha=0.8, varwidth = T)+
  geom_boxplot(aes(x=as.factor(month),y=yi_sf),fill="lightblue",alpha=0.8, varwidth = T)
```

```{r}

ggplot(stacked_effect, aes(x = as.factor(month), y = effectsize, fill = treatment)) +
  geom_boxplot(varwidth = T, alpha = 0.5) +
  geom_smooth(aes(color = treatment), method = "lm", se = FALSE) +
  geom_hline(yintercept = 0.5, alpha = 0.75)+
  geom_hline(yintercept = 0.25, alpha = 0.75)+
  geom_hline(yintercept = 0.75, alpha = 0.75)+
  #geom_jitter(aes(color = site_id), position = position_jitterdodge()) +
  theme_classic()
```

```{r}

duration <- full_data[,grep("site_id|(?<!_)year|er_duration",colnames(full_data),value = TRUE, perl = TRUE)]

stacked_effect_length <- distinct(merge(stacked_effect,
                        duration,
                        by = c("site_id","year"),
                        all = T))
```

```{r}
stacked_effect_length$duration <- ifelse(stacked_effect_length$er_duration_method <= 5, "0-5",
                                         ifelse(stacked_effect_length$er_duration_method <= 10, "6-10",
                                                ifelse(stacked_effect_length$er_duration_method <= 15, "11-15",
                                                       "16-20")))
                                         

ggplot(stacked_effect_length)+
  geom_boxplot(aes(x=as.factor(month), y = effectsize, fill = treatment), alpha = 0.5)+
  facet_wrap(~duration)+
  theme_classic()
```

```{r}

View(working_data[working_data$month == 1,])

```

