---
title: "effectsize_warming_year_round"
author: "Jan"
date: "2024-01-24"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# 23.01.2024

# Jan 
rm(list = ls())
source("D:/flux_db/metaanalysis_SF_OTC/code_data/data_cleaning.R") # get up-to date dataset







working_data$month <- month(working_data$flux_date)
working_data$week <- lubridate::isoweek(working_data$flux_date)
working_data$doy <- yday(working_data$flux_date)

working_data$monthseason <- ifelse(working_data$month <= 3,"NGS",
                                   ifelse(working_data$month <= 5, "Shoulder",
                                          ifelse(working_data$month <= 9, "GS",
                                                 ifelse(working_data$month <= 11, "Shoulder", "NGS"))))
```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r preps}
monthly <- working_data %>%
  group_by(site_id,flux_year,month) %>% 
  dplyr::summarise(n_ctl = sum(treatment == "CTL",na.rm=T),
                   n_otc = sum(treatment == "OTC",na.rm=T),
                   n_sf = sum(treatment == "SNOWFENCE",na.rm=T),
                   n_otc_sf = sum(treatment == "OTCxSNOWFENCE",na.rm=T),
                   m_ctl = mean(reco[treatment == "CTL"],na.rm=T),
                   m_otc = mean(reco[treatment == "OTC"],na.rm=T),
                   m_sf = mean(reco[treatment == "SNOWFENCE"],na.rm=T),
                   m_otc_sf = mean(reco[treatment == "OTCxSNOWFENCE"],na.rm=T),
                   s_ctl = sd(reco[treatment == "CTL"],na.rm=T),
                   s_otc = sd(reco[treatment == "OTC"],na.rm=T),
                   s_sf = sd(reco[treatment == "SNOWFENCE"],na.rm=T),
                   s_otc_sf = sd(reco[treatment == "OTCxSNOWFENCE"],na.rm=T))

monthly_otc <- monthly %>% filter(!is.na(m_otc))
monthly_otc <- monthly_otc[,-c(grep("sf",colnames(monthly_otc)))]

monthly_sf <- monthly %>% filter(!is.na(m_sf))
monthly_sf <- monthly_sf[,-c(grep("otc",colnames(monthly_sf)))]

monthly_otc_sf <- monthly %>% filter(!is.na(m_otc_sf))
monthly_otc_sf <- monthly_otc_sf[,c(1,2,3,c(grep("ctl|otc_sf",colnames(monthly_otc_sf))))]


```
lets go 
```{r effectsize calc}
otc_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_otc,
    # mean richness at invaded sites
    n1i = n_otc,
    # invaded site sample size
    sd1i = s_otc,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = monthly_otc # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_effect_sizes) <- gsub("yi", "yi_otc",colnames(otc_effect_sizes))
colnames(otc_effect_sizes) <- gsub("vi", "vi_otc",colnames(otc_effect_sizes))

sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_sf,
    # mean richness at invaded sites
    n1i = n_sf,
    # invaded site sample size
    sd1i = s_sf,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = monthly_sf # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(sf_effect_sizes) <- gsub("yi", "yi_sf",colnames(sf_effect_sizes))
colnames(sf_effect_sizes) <- gsub("vi", "vi_sf",colnames(sf_effect_sizes))

otc_sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_otc_sf,
    # mean richness at invaded sites
    n1i = n_otc_sf,
    # invaded site sample size
    sd1i = s_otc_sf,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = monthly_otc_sf # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_sf_effect_sizes) <- gsub("yi", "yi_otc_sf",colnames(otc_sf_effect_sizes))
colnames(otc_sf_effect_sizes) <- gsub("vi", "vi_otc_sf",colnames(otc_sf_effect_sizes))



```

# models

```{r yo}
#otc
otc_total <- rma.mv(yi_otc, vi_otc, 
                   random=list(~ 1 | site_id, 
                            ~ flux_year | site_id), 
                   struct="CAR",
                   mods = ~month,
                   data=otc_effect_sizes)
summary(otc_total)
forest(otc_total)
ggplot(otc_effect_sizes) +
  geom_boxplot(aes(x=as.factor(month), y= yi_otc))
  
  

#SF
sf_effect_sizes <- na.omit(sf_effect_sizes)
sf_total <- rma.mv(yi_sf, vi_sf, 
                   random=list(~ 1 | month, 
                            ~ flux_year | month), 
                   struct="CAR",
                   data=sf_effect_sizes)
summary(sf_total)
forest(sf_total)
ggplot(sf_effect_sizes) +
  geom_boxplot(aes(x=as.factor(month), y= yi_sf))

#otc_sf
otc_sf_total <- rma.mv(yi_otc_sf, vi_otc_sf, 
                   random=list(~ 1 | month, 
                            ~ flux_year | month), 
                   struct="CAR",
                   data=otc_sf_effect_sizes)
summary(otc_sf_total)
forest(otc_sf_total)
ggplot(otc_sf_effect_sizes) +
  geom_boxplot(aes(x=as.factor(month), y= yi_otc_sf))

```

```{r}
full_effect_size <- merge(otc_effect_sizes[,c(1,2,3,10,11)],
                          sf_effect_sizes[,c(1,2,3,10,11)],
                          by = c("site_id", "flux_year", "month"),
                          all = T)

full_effect_size <- merge(full_effect_size ,
                          otc_sf_effect_sizes[,c(1,2,3,10,11)],
                          by = c("site_id", "flux_year", "month"),
                          all = T)

stacked_effect <- full_effect_size %>% 
  gather(treatment, effectsize, yi_otc,yi_sf,yi_otc_sf)

```

hello i changed something


```{r}
ggplot(full_effect_size)+
  geom_boxplot(aes(x=as.factor(month),y=yi_otc_sf),fill="red",alpha=0.8, varwidth = T)+
  geom_boxplot(aes(x=as.factor(month),y=yi_otc),fill="lightgreen",alpha=0.8, varwidth = T)+
  geom_boxplot(aes(x=as.factor(month),y=yi_sf),fill="lightblue",alpha=0.8, varwidth = T)
```

```{r}
ggplot(stacked_effect[stacked_effect$month != 4,], aes(x = month, y = effectsize, color = treatment)) +
  geom_point() +
  geom_smooth(method = "loess") +
  geom_smooth(aes(color = treatment), method = "lm", se = FALSE) +
  geom_hline(yintercept = 0.5, alpha = 0.75)+
  geom_hline(yintercept = 0.25, alpha = 0.75)+
  geom_hline(yintercept = 0.75, alpha = 0.75)+
  #geom_jitter(aes(color = site_id), position = position_jitterdodge()) +
  theme_classic()
```

```{r preps}
weekly <- working_data %>%
  group_by(site_id,flux_year,week) %>% 
  dplyr::summarise(n_ctl = sum(treatment == "CTL",na.rm=T),
                   n_otc = sum(treatment == "OTC",na.rm=T),
                   n_sf = sum(treatment == "SNOWFENCE",na.rm=T),
                   n_otc_sf = sum(treatment == "OTCxSNOWFENCE",na.rm=T),
                   m_ctl = mean(reco[treatment == "CTL"],na.rm=T),
                   m_otc = mean(reco[treatment == "OTC"],na.rm=T),
                   m_sf = mean(reco[treatment == "SNOWFENCE"],na.rm=T),
                   m_otc_sf = mean(reco[treatment == "OTCxSNOWFENCE"],na.rm=T),
                   s_ctl = sd(reco[treatment == "CTL"],na.rm=T),
                   s_otc = sd(reco[treatment == "OTC"],na.rm=T),
                   s_sf = sd(reco[treatment == "SNOWFENCE"],na.rm=T),
                   s_otc_sf = sd(reco[treatment == "OTCxSNOWFENCE"],na.rm=T))

weekly_otc <- na.omit(weekly %>% filter(!is.na(m_otc)))
weekly_otc <- weekly_otc[,-c(grep("sf",colnames(weekly_otc)))]

weekly_sf <- na.omit(weekly %>% filter(!is.na(m_sf)))
weekly_sf <- weekly_sf[,-c(grep("otc",colnames(weekly_sf)))]

weekly_otc_sf <- na.omit(weekly %>% filter(!is.na(m_otc_sf)))
weekly_otc_sf <- weekly_otc_sf[,c(1,2,3,c(grep("ctl|otc_sf",colnames(weekly_otc_sf))))]


```
lets go 
```{r effectsize calc}
otc_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_otc,
    # mean richness at invaded sites
    n1i = n_otc,
    # invaded site sample size
    sd1i = s_otc,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = weekly_otc # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_effect_sizes) <- gsub("yi", "yi_otc",colnames(otc_effect_sizes))
colnames(otc_effect_sizes) <- gsub("vi", "vi_otc",colnames(otc_effect_sizes))

sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_sf,
    # mean richness at invaded sites
    n1i = n_sf,
    # invaded site sample size
    sd1i = s_sf,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = weekly_sf # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(sf_effect_sizes) <- gsub("yi", "yi_sf",colnames(sf_effect_sizes))
colnames(sf_effect_sizes) <- gsub("vi", "vi_sf",colnames(sf_effect_sizes))

otc_sf_effect_sizes <-
  escalc( # This is the function in metafor that allows us to calculate an effect size for each row in a database
    "SMD",
    # Specify the effect size we want to calculate. In this case SMD for Standardized mean difference
    m1i = m_otc_sf,
    # mean richness at invaded sites
    n1i = n_otc_sf,
    # invaded site sample size
    sd1i = s_otc_sf,
    # invaded site SD
    m2i = m_ctl,
    # mean richness at control sites
    n2i = n_ctl,
    # control site sample size
    sd2i = s_ctl,
    # control site SD
    data = weekly_otc_sf # This is where the escalc function can find all the data for our meta-analysis
  )

colnames(otc_sf_effect_sizes) <- gsub("yi", "yi_otc_sf",colnames(otc_sf_effect_sizes))
colnames(otc_sf_effect_sizes) <- gsub("vi", "vi_otc_sf",colnames(otc_sf_effect_sizes))



```

# models

```{r yo}
#otc
otc_total <- rma.mv(yi_otc, vi_otc, 
                   random=list(~ 1 | site_id, 
                            ~ flux_year | site_id), 
                   struct="CAR",
                   mods = ~week,
                   data=otc_effect_sizes)
summary(otc_total)
forest(otc_total)
ggplot(otc_effect_sizes) +
  geom_point(aes(x=as.factor(week), y= yi_otc))

``` 
  
```{r yo}
#SF
sf_effect_sizes <- na.omit(sf_effect_sizes)
sf_total <- rma.mv(yi_sf, vi_sf, 
                   random=list(~ 1 | week, 
                            ~ flux_year | week), 
                   struct="CAR",
                   data=sf_effect_sizes)
summary(sf_total)
forest(sf_total)
ggplot(sf_effect_sizes) +
  geom_boxplot(aes(x=as.factor(week), y= yi_sf))

```

```{r yo}
#otc_sf
otc_sf_total <- rma.mv(yi_otc_sf, vi_otc_sf, 
                   random=list(~ 1 | week, 
                            ~ flux_year | week), 
                   struct="CAR",
                   data=otc_sf_effect_sizes)
summary(otc_sf_total)
forest(otc_sf_total)
ggplot(otc_sf_effect_sizes) +
  geom_boxplot(aes(x=as.factor(week), y= yi_otc_sf))

```

```{r}
full_effect_size <- merge(otc_effect_sizes[,c(1,2,3,10,11)],
                          sf_effect_sizes[,c(1,2,3,10,11)],
                          by = c("site_id", "flux_year", "week"),
                          all = T)

full_effect_size <- merge(full_effect_size ,
                          otc_sf_effect_sizes[,c(1,2,3,10,11)],
                          by = c("site_id", "flux_year", "week"),
                          all = T)

stacked_effect <- full_effect_size %>% 
  gather(treatment, effectsize, yi_otc,yi_sf,yi_otc_sf)

```

hello i changed something


```{r}
ggplot(full_effect_size)+
  geom_boxplot(aes(x=as.factor(week),y=yi_otc_sf),fill="red",alpha=0.8, varwidth = T)+
  geom_boxplot(aes(x=as.factor(week),y=yi_otc),fill="lightgreen",alpha=0.8, varwidth = T)+
  geom_boxplot(aes(x=as.factor(week),y=yi_sf),fill="lightblue",alpha=0.8, varwidth = T)
```

```{r}
ggplot(stacked_effect, aes(x = week, y = effectsize, color = treatment)) +
  geom_point() +
  geom_smooth(method = "loess")+
  geom_smooth(aes(color = treatment), method = "lm", se = FALSE) +
  geom_hline(yintercept = 0.5, alpha = 0.75)+
  geom_hline(yintercept = 0.25, alpha = 0.75)+
  geom_hline(yintercept = 0.75, alpha = 0.75)+
  #geom_jitter(aes(color = site_id), position = position_jitterdodge()) +
  theme_classic()
```

